version: 2

sources:
    - name: DST_DB
      description: 'Ceci est l''examen DBT.'
      database: DST_DB
      schema: EXAM_SNOWFLAKE
      tables:
        - name: ALBUM
          description: 'Les albums.'
        - name: ARTIST
          description: 'Les artistes.'
        - name: GENRE
          description: 'Les genres de musiques.'
        - name: MEDIATYPE
          description: 'Les types de medias.'
        - name: PLAYLIST
          description: 'Les playlists.'
        - name: PLAYLISTTRACK
          description: 'Les pistes constituants les playlists.'
        - name: TRACK
          description: 'Les pistes.'

models:
  - name: dim_mediatype
    description: "Table Dimension des types de media"
    columns:
      - name: mediatype_id
        description: "Clef primaire de la table."
        data_type: NUMBER
        data_tests:
          - unique
          - not_null
      - name: name
        description: 'Nom du type de media.'
        data_type: VARCHAR
        data_tests:
          - not_null