version: 2

models:
  - name: question1
    description: "Donnez les titres des albums qui ont plus de 1 CD."
    columns:
      - name: title
        description: "Titre de l''album'."
        data_type: VARCHAR

  - name: question2
    description: "Donnez les morceaux produits en 2000 ou en 2002."
    columns:
      - name: track_id
        description: "ID de la piste."
        data_type: NUMBER

  - name: question3
    description: "Donnez le nom et le compositeur des morceaux de Rock et de Jazz."
    columns:
      - name: name
        description: "Nom du morceau."
        data_type: VARCHAR

  - name: question4
    description: "Donnez les 10 albums les plus longs."
    columns:
      - name: total_time
        description: "Temps total."
        data_type: NUMBER

  - name: question5
    description: "Donnez le nombre d'albums produits pour chaque artiste."
    columns:
      - name: artist_name
        description: "Nom de l'artiste"
        data_type: VARCHAR

  - name: question6
    description: "Donnez le nombre de morceaux produits par chaque artiste."
    columns:
      - name: artist_name
        description: "Nom de l'artiste"
        data_type: VARCHAR

  - name: question7
    description: "Donnez le genre de musique le plus écouté dans les années 2000."
    columns:
      - name: total
        description: "Nombre occurences morceau dans les playlists"
        data_type: NUMBER
      
  - name: question8
    description: "Donnez les noms de toutes les playlists où figurent des morceaux de plus de 4 minutes."
    columns:
      - name: name
        description: "Nom des playlists"
        data_type: VARCHAR

  - name: question9
    description: "Donnez les morceaux de Rock dont les artistes sont en France."
    columns:
      - name: track_id
        description: "ID les pistes"
        data_type: NUMBER

  - name: question10
    description: "Donnez la moyenne des tailles des morceaux par genre musical."
    columns:
      - name: name
        description: "Nom du genre"
        data_type: VARCHAR

  - name: question11
    description: "Donnez les playlist où figurent des morceaux d'artistes nés avant 1990."
    columns:
      - name: name
        description: "Nom de la playlist"
        data_type: VARCHAR


